.

diff --git a/fim b/fim
--- a/fim
+++ b/fim
@@ -4,29 +4,55 @@
 # Date: December 2021
 
 # fim: Searches from the current or a specified directory for a file, opens the file in vim if it 
-
 # is found.
 
 # exit 1: usage error
-# exit 2: invalid file option
+# exit 2: invalid option
+# exit 3: specified option exists, but has no functionality yet.
 
-## check for at least one, but no more than two command line arguments.
-if [[ "$#" -lt 1 ]]; then
-    echo "Usage: fim [directory] <filename>"
-    exit 1
-fi
-if [[ "$#" -gt 2 ]]; then
-    echo "Usage: fim [directory] <filename>"
+if [[ $# -lt 1 ]]; then
+    echo "Usage: fim [option] [directory] <filename>"
     exit 1
 fi
 
-getOption () {
+if [[ $# -gt 3 ]]; then
+    echo "Usage: fim [option] [directory] <filename>"
+    exit 1
+fi
+
+## options are checked here, and saved for later use if the option is valid, since other code has to 
+## happen before the option matters, and there is no need for the program to do anything if an option 
+## is invalid.
+if [[ $# -ge 2 ]]; then
+    if [[ ${1:0:1} == "-" ]]; then
+        case $1 in
+            -a)     option="$1" ;;
+            -a1)    option="$1" ;;
+            --list) echo "[-a] [-a1]"
+                    exit 0
+                    ;;
+            *)      echo "Invalid option: $1"
+                    exit 2
+                    ;;
+        esac
+        shift
+    fi
+
+    ## because of the nature of the current available options, it doesn't make sense to have more than 
+    ## one option active at a time.
+    if [[ ${1:0:1} == "-" ]]; then 
+        echo "Only one option can be valid at a time."
+        exit 1
+    fi
+fi
+
+openFile () {
     read -rp "$1" num
     re='^[+-]?[0-9]+$'
     if ! [[ $num =~ $re ]]; then
-        getOption "NAN, try again > "
+        openFile "NAN, try again > "
     elif [[ $num -ge ${#matches[@]} ]]; then
-        getOption "Invalid option, try again > "
+        openFile "Invalid option, try again > "
     elif [[ $num -lt 0 ]]; then 
         true
     else
@@ -34,54 +60,45 @@ getOption () {
     fi
 }
 
-## if one command line argument.
-if [ "$#" -eq 1 ]; then
-    file="$1"
-
-    #find ./ -name "$file" -exec vim {} \; 2>/dev/null
-    #find ./ -name "$file" 2>/dev/null | | grep -q "$file"
-    #find ./ -name "$file" -exec vim {} \; 2>&1 | grep -v "Permission denied"
-
-    find ./ -name "$file" 2>&1 | grep -v "Permission denied" | grep -q "$file"
+getFiles () {
+    find "$path" -name "$file" 2>&1 | grep -v "Permission denied" | grep -q "$file"
     code="$?"
     if [[ "$code" -eq 0 ]]; then
         matches=()
-        for line in $(find ./ -name "$file" 2>&1 | grep -v "Permission denied"); do
+        for line in $(find "$path" -name "$file" 2>&1 | grep -v "Permission denied"); do
             matches+=($line)
-            #vim "$line"
         done
-        count=0
-        for match in "${matches[@]}"; do
-            echo "$count) $match"
-            ((count++))
-        done
-        getOption "Which file do you want to open? > "
-        code="$num"
     fi
+}
+
+## if one command line argument.
+if [ "$#" -eq 1 ]; then
+    path="./"
+    file="$1"
+else
+    path="$1"
+    file="$2"
 fi
 
-## if two command line arguments.
-if [ "$#" -eq 2 ]; then
-    file="$2"
+getFiles
 
-    #find "$1" -name "$file" -exec vim {} \; 2>/dev/null
-    #find "$1" -name "$file" 2>/dev/null | grep -q "$1"
-    #find "$1" -name "$file" -exec vim {} \; 2>&1 | grep -v "Permission denied"
-
-    find "$1" -name "$file" 2>&1 | grep -v "Permission denied" | grep -q "$file"
-    code="$?"
-    if [[ "$code" -eq 0 ]]; then
-        for line in $(find "$1" -name "$file" 2>&1 | grep -v "Permission denied"); do
-            #vim "$line"
-            matches+=($line)
-        done
+## no reason to do anything if no files were found
+if [[ $code -eq 0 ]]; then
+    if [[ -z "$option" ]]; then
         count=0
         for match in "${matches[@]}"; do
             echo "$count) $match"
             ((count++))
         done
-        getOption "Which file do you want to open? > "
+        openFile "Which file do you want to open? > "
         code="$num"
+    elif [[ $option == "-a" ]]; then
+        .
+    elif [[ $option == "-a1" ]]; then
+        .
+    else
+        echo "Option found: $option. No functionality yet."
+        exit 3
     fi
 fi
 
