Initial tar stuff created and working

diff --git a/tarStuff/tabz b/tarStuff/tabz
--- a/tarStuff/tabz
+++ b/tarStuff/tabz
@@ -7,3 +7,58 @@
 
 # exit 1: usage error
 
+## no command line args
+if [[ $# -lt 1 ]]; then
+    echo "Usage: tabz [OPTIONS] <file>"
+    exit 1
+fi
+
+hlp () {
+    ## display the help menu
+    echo "tabz, Make tar easier"
+    echo -e "\nUSAGE:"
+    echo -e "\ttabz [OPTIONS] <file>" | expand -t4
+    echo -e "\nOPTIONS:" | expand -t4
+    echo -e "\t-h, --help\t\t\tDisplay this menu and exit" | expand -t4
+    echo -e "\t\t--list\t\t\tList all options" | expand -t4
+    echo -e "\n\t-n\t\t\t\t\tName the tar file" | expand -t4
+}
+
+## no options present
+if [[ $# -eq 1 ]]; then
+    file="$(echo $1 | sed 's/\///')"
+fi
+
+##  if an option is present
+if [[ ${1:0:1} == "-" ]]; then
+
+    case $1 in
+        -n)
+            shift
+            file=$1
+            shift
+            ;;
+
+        -h)
+            hlp
+            exit 0
+            ;;
+
+        --help)
+            hlp
+            exit 0
+            ;;
+
+        --list)
+            echo "[-n] [-h, --help] [--list]"
+            exit 0
+            ;;
+
+        *)
+            echo "tabz: invalid option -- $1"
+            exit 1
+            ;;
+    esac
+fi
+
+tar -cvjf "$file".tbz $1
diff --git a/tarStuff/untar b/tarStuff/untar
--- a/tarStuff/untar
+++ b/tarStuff/untar
@@ -7,3 +7,64 @@
 
 # exit 1: usage error
 
+## if no command line args
+if [[ $# -lt 1 ]]; then
+    echo "Usage: untar <file(s)>"
+    exit 1
+fi
+
+hlp () {
+    ## display the help menu
+    echo "untar, Detect and untar tarballs"
+    echo -e "\nUSAGE:"
+    echo -e "\tuntar <file(s)>" | expand -t4
+    echo -e "\nOPTIONS:" | expand -t4
+    echo -e "\t-h, --help\t\t\tDisplay this menu and exit" | expand -t4
+    echo -e "\t\t--list\t\t\tList all options" | expand -t4
+}
+
+## detect file extension
+fiex=$1
+for fiex in "$@"; do
+    case "$fiex" in
+        *.tar)      tar -xvf $fiex
+                    exit $?
+                    ;;
+
+        *.tar.gz)   tar -xvf $fiex
+                    exit $?
+                    ;;
+
+        *.tgz)      tar -xvf $fiex
+                    exit $?
+                    ;;
+
+        *.tar.bz2)  tar -xvf $fiex
+                    exit $?
+                    ;;
+
+        *.bz2)      tar -xvf $fiex
+                    exit $?
+                    ;;
+
+        *.tar.tbz)  tar -xvf $fiex
+                    exit $?
+                    ;;
+
+        *.tbz)      tar -xvf $fiex
+                    exit $?
+                    ;;
+
+        *.tar.tb2)  tar -xvf $fiex
+                    exit $?
+                    ;;
+
+        *.tb2)      tar -xvf $fiex
+                    exit $?
+                    ;;
+
+        *)          echo "Failure: unkown extension on file: $fiex"
+                    exit 2
+                    ;;
+    esac
+done
